source "https://rubygems.org"

# Rails
gem "rails", "~> 8.1.1"

# Database
gem "pg", "~> 1.1"

# Web server
gem "puma", ">= 5.0"

# Timezone data for Windows / JRuby
gem "tzinfo-data", platforms: %i[windows jruby]

# Rails internal infrastructure
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Performance / boot
gem "bootsnap", require: false

# Deployment / container
gem "kamal", require: false
gem "thruster", require: false

# Active Storage
gem "image_processing", "~> 1.2"

# Environment variables
gem "dotenv-rails", groups: %i[development test]

gem 'rack-cors'

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
